FROM php:8.3-alpine3.22

LABEL mantainer="John Edisson Ortiz"
LABEL email="j.ortiz3109@gmail.com"
LABEL org.opencontainers.image.description="PHP image for Laravel development"
LABEL org.opencontainers.image.vendor="John Edisson Ortiz <j.ortiz3109@gmail.com>"

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions redis sockets bcmath pdo_mysql pdo_pgsql intl
RUN install-php-extensions @composer